version: "3.8"
services:
 strapi:
    container_name: strapi
    build: .
    image: strapi:latest
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: postgresql
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: jazzintoronto
      DATABASE_USERNAME: jazzintoronto
      DATABASE_PASSWORD: jazzintoronto
      JWT_SECRET: local
      ADMIN_JWT_SECRET: local
      APP_KEYS: 'local1,local2'
      NODE_ENV: development
    volumes:
      - /app:./srv/app
    ports:
      - "1337:1337"
    networks:
      - strapi
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: jazzintoronto
      POSTGRES_PASSWORD: jazzintoronto
      POSTGRES_DB: jazzintoronto
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
