version: "3.8"
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: jazzintoronto
      POSTGRES_PASSWORD: jazzintoronto
      POSTGRES_DB: jazzintoronto
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
